[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nba-crunch"
version = "0.1.0"
description = "Analysis of NBA free throw shooting in crunch time"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["nba_crunch*"]